plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-2.4.1.cjs

packageExtensions:
  "antd-dayjs-webpack-plugin@*":
    dependencies:
      loader-utils: "^2.0.0"
  "@2fd/ant-design-icons@*":
    dependencies:
      tslib: "^2.0.3"