packageExtensions:
  "@2fd/ant-design-icons@*":
    dependencies:
      tslib: ^2.0.3
  antd-dayjs-webpack-plugin@*:
    dependencies:
      loader-utils: ^2.0.0
  babel-preset-react-app@*:
    dependencies:
      "@babel/plugin-proposal-private-property-in-object": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.3.0.cjs
