name: malva-env
channels:
    - conda-forge
    - bioconda
dependencies:
    - snakemake-minimal=5.32.2
    - mafft=7.487
    - htslib=1.10.2
    - sdsl-lite=2.1.1
    - kmc=3.1.2rc1
    - samtools=1.10
    - pysam=0.16.0.1
    - gffutils=0.10.1
    - snp-sites=2.5.1
    - snpeff=5.0
    - csvkit=1.0.5