name: malva-env
channels:
    - defaults
    - bioconda
    - conda-forge
dependencies:
    - snakemake-minimal
    - mafft
    - kmc
    - samtools
    - pysam
    - gffutils
    - snp-sites
    # - malva
