name: malva-env
channels:
    - defaults
    - bioconda
    - conda-forge
dependencies:
    - snakemake-minimal=5.14.0
    - mafft=7.463
    - kmc=3.1.2rc1
    - samtools=1.9
    - pysam=0.15.4
    - gffutils=0.10.1
    - snp-sites=2.5.1
    - malva=1.3.1
    - snpeff=4.5covid19