import React, { useCallback, useState } from 'react';

import { useNavigate } from 'react-router-dom';

import {
  Form,
  Button,
  Upload,
  message,
  InputNumber,
  Select,
  Input,
  Collapse,
} from 'antd';

import { UploadOutlined } from '@ant-design/icons';

import { defaultMalvaParams } from 'app-config';
import { ButtonPanel, Error, Loading, showError } from 'components';
import { normFile, getFalse } from 'utils';
import params from 'utils/call-params';

function CallNew({ createCall, vcfs }) {
  const [loading, setLoading] = useState(false);
  const navigate = useNavigate();
  const onFinish = useCallback(
    ({ file, ...values }) => {
      new Promise((resolve, reject) => {
        setLoading(true);
        createCall(file[0], values, resolve, reject);
      }).then(
        (call) => {
          setLoading(false);
          message.success('Job submission successful!');
          navigate(`../${call.id}`);
        },
        (error) => {
          setLoading(false);
          return showError(error);
        }
      );
    },
    [createCall, navigate]
  );

  const onClickCancel = useCallback(() => navigate(-1), [navigate]);
  if (vcfs.rejected) {
    return <Error reason={vcfs.reason} />;
  }
  if (!vcfs.fulfilled) {
    return <Loading />;
  }
  return (
    <>
      <h1>Perform a new variant call</h1>
      <Form
        initialValues={defaultMalvaParams}
        layout="vertical"
        name="newvcf"
        onFinish={onFinish}
      >
        <Form.Item
          label="Alias"
          name="alias"
          extra="An alias for the job, so that you can easily retrieve it in the future. Autogenerated if missing."
        >
          <Input />
        </Form.Item>

        <Form.Item
          label="Description"
          name="description"
          rules={[
            {
              required: true,
              message: 'Please provide a brief description of the job!',
            },
          ]}
          extra="A brief description of the job, so that you can remember how it has been generated."
        >
          <Input.TextArea />
        </Form.Item>

        <Form.Item
          name="file"
          label="Sample sequences (FASTA/Q)"
          valuePropName="fileList"
          getValueFromEvent={normFile}
          rules={[
            {
              required: true,
              message: 'Please select a set of sequences!',
            },
          ]}
        >
          <Upload name="file" beforeUpload={getFalse}>
            <Button icon={<UploadOutlined />}>Select file</Button>
          </Upload>
        </Form.Item>

        <Form.Item
          label={params.vcf.label}
          name="vcf"
          rules={[
            {
              required: true,
              message: 'Please provide reference VCF!',
            },
          ]}
          extra={params.vcf.extra}
        >
          <Select>
            {vcfs.value.content.map((vcf) => (
              <Select.Option key={vcf.id} value={vcf.id}>
                {vcf.alias}
              </Select.Option>
            ))}
          </Select>
        </Form.Item>

        <Form.Item
          label={params.cores.label}
          name="cores"
          rules={[
            {
              required: true,
              message: 'Please provide a valid number!',
            },
          ]}
          extra={params.cores.extra}
        >
          <InputNumber min={1} type="number" />
        </Form.Item>

        <Collapse>
          <Collapse.Panel header="Advanced parameters" key="adv" forceRender>
            <Form.Item
              label={params.minocc.label}
              name="minocc"
              rules={[
                {
                  required: true,
                  message: 'Please provide a valid number!',
                },
              ]}
              extra={params.minocc.extra}
            >
              <InputNumber min={10} type="number" />
            </Form.Item>

            <Form.Item
              label={params.maxocc.label}
              name="maxocc"
              rules={[
                {
                  required: true,
                  message: 'Please provide a valid number!',
                },
              ]}
              extra={params.maxocc.extra}
            >
              <InputNumber min={1} type="number" />
            </Form.Item>

            <Form.Item
              label={params.lenkmers.label}
              name="lenkmers"
              rules={[
                {
                  required: true,
                  message: 'Please provide a valid number!',
                },
              ]}
              extra={params.lenkmers.extra}
            >
              <InputNumber min={1} type="number" />
            </Form.Item>

            <Form.Item
              label={params.maxmem.label}
              name="maxmem"
              rules={[
                {
                  required: true,
                  message: 'Please provide a valid number!',
                },
              ]}
              extra={params.maxmem.extra}
            >
              <InputNumber min={1} type="number" />
            </Form.Item>
          </Collapse.Panel>
        </Collapse>
        <ButtonPanel>
          <Button type="primary" htmlType="submit" loading={loading}>
            Submit
          </Button>
          <Button type="default" onClick={onClickCancel}>
            Cancel
          </Button>
        </ButtonPanel>
      </Form>
    </>
  );
}

export default CallNew;
