workdir: example/2nd_jobid
reference: example/NC_045512.2.fa
vcf: example/1st_jobid/vcf/run.cleaned.vcf
sample: example/sample.fq
minocc: 5
maxocc: 50000
malvak: 31
maxmem: 4
gtf: example/GCF_009858895.2_ASM985889v3_genomic.gff
cores: 4