workdir: example/2nd_jobid
reference: example/1st_jobid/snpsites/run.pseudoreference.fa
vcf: example/1st_jobid/vcf/run.cleaned.vcf
sample: example/sample.fq
minocc: 5
maxocc: 750
lenkmers: 43
malvak: 35
cores: 4
maxmem: 4
